version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=KEY
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=sqlite:///database.db
    volumes:
      - ./database:/app
    depends_on:
      - db

  db:
    image: "sqlite"
    volumes:
      - ./database:/var/lib/sqlite
